# let's toss a coin

One tosses a coin 20 times and 15 heads come up! Is the coin fair?

#### Hypothesis 1: This coin is biased
#### Hypothesis 2: This is just by chance!
    
Statistical Method

P(H) = ?

P(HH) = ?

P(THH) = ?

## $P(x)=\frac{n!}{x!(n-x)!}p^x(1-p^{n-x})$

# [0,1,1,0,0,1,0,1,0,1,0,1,0,1,1,0,1,0]

In [48]:
from numpy import math 
fc = math.factorial

fc(20)/(fc(15)*fc(5)) * 0.5**15 * 0.5**5

0.0147857666015625

In [2]:
import numpy as np

In [19]:
np.random.binomial(20,0.5)

12

In [32]:
np.random.binomial(20,0.5)==15

False

In [72]:
ntry = 100000
np.sum(np.random.binomial(20,0.5,ntry)==15)/ntry

0.01484

# Persian carpet company!


#### Hypothesis 1: The optimization didn't work :(

#### Hypothesis 2: Yesss! It works!

In [187]:
before_opt = np.array([23, 21, 19, 24, 35, 17, 18, 24, 33, 27, 21, 23])
after_opt = np.array([31, 28, 19, 24, 32, 27, 16, 41, 23, 32, 29, 33])

In [188]:
before_opt.mean(),after_opt.mean()

(23.75, 27.916666666666668)

In [189]:
diff_obs = after_opt.mean()-before_opt.mean()
diff_obs

4.166666666666668

In [190]:
experiment = np.append(before_opt,after_opt)
experiment

array([23, 21, 19, 24, 35, 17, 18, 24, 33, 27, 21, 23, 31, 28, 19, 24, 32,
       27, 16, 41, 23, 32, 29, 33])

In [191]:
diffs = []
for i in range(10000):
    np.random.shuffle(experiment)
    set1 = experiment[:10]
    set2 = experiment[10:]
    diffs.append(set1.mean()-set2.mean())
diffs = np.array(diffs)

In [192]:
np.mean(diffs<diff_obs)*100

94.0

In [193]:
before_opt = np.array([230, 210, 190, 240, 350, 170, 180, 240, 330, 270, 210, 230])
after_opt = np.array([310, 180, 190, 240, 220, 240, 160, 410, 130, 320, 290, 210])

In [194]:
diff_obs = after_opt.mean()-before_opt.mean()
diff_obs

4.166666666666657

In [195]:
experiment = np.append(before_opt,after_opt)
experiment

array([230, 210, 190, 240, 350, 170, 180, 240, 330, 270, 210, 230, 310,
       180, 190, 240, 220, 240, 160, 410, 130, 320, 290, 210])

In [196]:
diffs = []
for i in range(10000):
    np.random.shuffle(experiment)
    set1 = experiment[:10]
    set2 = experiment[10:]
    diffs.append(set1.mean()-set2.mean())
diffs = np.array(diffs)

In [197]:
np.mean(diffs<diff_obs)*100

57.45

### What the ?!?!?!

In [198]:
before_opt = np.array([23, 21, 19, 24, 35, 17, 18, 24, 33, 27, 21, 23])
after_opt = np.array([31, 28, 19, 24, 32, 27, 16, 41, 23, 32, 29, 33])

print ((np.mean(after_opt) - np.mean(before_opt))/np.mean(before_opt)*100)

17.543859649122812


In [199]:
before_opt = np.array([230, 210, 190, 240, 350, 170, 180, 240, 330, 270, 210, 230])
after_opt = np.array([310, 180, 190, 240, 220, 240, 160, 410, 130, 320, 290, 210])

print ((np.mean(after_opt) - np.mean(before_opt))/np.mean(before_opt)*100)

1.7543859649122768


# Confidence Interval

In [130]:
before_opt = np.array([23, 21, 19, 24, 35, 17, 18, 24, 33, 27, 21, 23])
after_opt = np.array([31, 28, 19, 24, 32, 27, 16, 41, 23, 32, 29, 33])

In [131]:
random_before_opt = np.random.choice(before_opt, size=10, replace=True)
random_before_opt

array([24, 24, 23, 18, 23, 27, 18, 27, 21, 17])

In [142]:
diffs = []
for i in range(1000):
    random_before_opt = np.random.choice(before_opt, size=10, replace=True)
    random_after_opt = np.random.choice(after_opt, size=10, replace=True)
    diffs.append(np.mean(random_after_opt) - np.mean(random_before_opt))

In [143]:
np.percentile(diffs, [5,95])

array([-0.6,  8.2])